### ISSUE TITLE
Multiple issues with bank holidays

### ISSUE THREAD

**Issue by bigheadsmith** [ashlessscythe/timeoff-alien#14]
Bank Holidays can be added but not amended or deleted
- add bank holiday works correctly
- amend date of bank holiday, message says successful, but date remains the same
- delete bank holiday, get page not found

Bank holidays not respecting company date format #17
- Set date format to YYYY-MM-DD, set 1st March as BH, works correctly
- Set date format as DD-MM-YYYY, set 1st Feb as BH, incorrectly saves as 2nd Jan

**Comment by bigheadsmith** [comment]
fixed with #20

**Comment by bigheadsmith** [comment]
Deletions work fine, not amendments

**Comment by ashlessscythe** [comment]
fixed with commit [af998cd](https://github.com/ashlessscythe/timeoff-alien/commit/af998cd1b0d1528fa8436c659b8635a472efa809)

Please verify and close

**Comment by bigheadsmith** [comment]
Looks good
