### ISSUE TITLE
Minor: Company-wide schedule buttons

### ISSUE THREAD

**Issue by bigheadsmith** [ashlessscythe/timeoff-alien#7]
The company-wide schedule is being saved correctly, but the "checked" attribute and "active" class is not being applied to the buttons on the General Settings page.

The schedule buttons are shown correctly on the User/Employee page regardless of whether it is set to company-wide or override

**Comment by ashlessscythe** [comment]
fixed in commit [457dcf7](https://github.com/ashlessscythe/timeoff-alien/commit/457dcf7d8cbbbe33b448e79ba5b4602af0351d59)
